config/routes.rb
Rails.application.routes.draw do

  resources :password_resets, only: [:create, :edit, :update]

  root 'entries#landing'

  post 'entries/upload' => 'entries#upload'
  post 'entries/:id/analyse' => 'entries#analyse', as: :analyse
  post 'entries/analyse_all' => 'entries#analyse_all', as: :analyse_all
  post 'users/:user_id/reports/:id/export_csv' => 'reports#export_csv', as: :export_csv
  get 'entries/delete_all' => 'entries#delete_all'

  resources :user_sessions
  resources :entries
  resources :users do
    resources :reports
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_filter :require_login

  # request password reset.
  # you get here when the user entered his email in the reset password form and submitted it.
  def create 
    @user = User.find_by(email: (params[:email]))
    # This line sends an email to the user with instructions on how to reset their password (a url with a random token)
    if @user 
      @user.deliver_reset_password_instructions! 
    end

    # Tell the user instructions have been sent whether or not email was found.
    # This is to not leak information to attackers about which emails exist in the system.
    redirect_to(root_path, :notice => 'Instructions have been sent to your email.')
  end


  # This is the reset password form.
  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end
  end

  # This action fires when the user has sent the reset password form.
  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end

    # the next line makes the password confirmation validation work
    @user.password_confirmation = params[:user][:password_confirmation]
    # the next line clears the temporary token and updates the password
    if @user.change_password!(params[:user][:password])
      redirect_to(root_path, :notice => 'Password was successfully updated.')
    else
      render :action => "edit"
    end
  end       
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/create.html.erb
<h1>PasswordResets#create</h1>
<p>Find me in app/views/password_resets/create.html.erb</p>

app/views/password_resets/edit.html.erb
<div class="page-header">
  <h1>Choose a new password</h1>
</div>
<%= form_for @user, :url => password_reset_path(@token), :html => {:method => :put, :class => "form-group"} do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class='row'>
  <div class="col-md-6 col-md-offset-3">
    <%= f.label :email %></br>
    <%= f.text_field :email, readonly: true,:class => "form-control" %>
  </div>
</div>
<div class='row'>
  <div class="col-md-6 col-md-offset-3">
    <%= f.label :password %></br>
    <%= f.password_field :password, :class => "form-control" %>
  </div>
</div>
<div class='row'>  
  <div class="col-md-6 col-md-offset-3">
    <%= f.label :password_confirmation %></br>
    <%= f.password_field :password_confirmation, :class => "form-control" %>
  </div>
</div>
</br>
<div class='row'>
  <div class="col-md-6 col-md-offset-3">
    <%= f.submit "Submit" ,class: "btn btn-w-m btn-info" %>
  </div>
</div>
<% end %>

app/views/password_resets/update.html.erb
<h1>PasswordResets#update</h1>
<p>Find me in app/views/password_resets/update.html.erb</p>