config/routes.rb
Rails.application.routes.draw do

  resources :password_resets, only: [:create, :edit, :update]

  root 'entries#landing'

  post 'entries/upload' => 'entries#upload'
  post 'entries/:id/analyse' => 'entries#analyse', as: :analyse
  post 'entries/analyse_all' => 'entries#analyse_all', as: :analyse_all
  post 'users/:user_id/reports/:id/export_csv' => 'reports#export_csv', as: :export_csv
  get 'entries/delete_all' => 'entries#delete_all'

  resources :user_sessions
  resources :entries
  resources :users do
    resources :reports
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  
  belongs_to :user

  validates_presence_of :company_name, :ticker, :event_name, :date, :speaker_name, :wcount, :transcript
  validates :event_name, uniqueness: {:scope => [:speaker_name, :company_name, :user_id]}
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  include UploadHelper
  skip_before_filter :require_login, only: [:landing]
  
  def landing

  end

  def index
    @entries = Entry.all
    respond_to do |format|
      format.html 
      # format.json { 
      #   render json: EntryDatatable.new(view_context)
      # }
    end
  end

  def show
    @entry = Entry.find(params[:id])
    unless @entry.insights.nil?
      @big5 = @entry.insights["tree"]["children"][0]
      @needs = @entry.insights["tree"]["children"][1]
      @values = @entry.insights["tree"]["children"][2]
    end
  end

  def new
    @entry = Entry.new
  end

  def analyse
    @entry = Entry.find(params[:id])
    profile_api_url = "#{Figaro.env.bluemix_url}/v2/profile"
    client = RestClient::Resource.new(profile_api_url, Figaro.env.bluemix_username, Figaro.env.bluemix_password)
    insights = client.post @entry.transcript, :content_type => "text/plain;charset=utf-8"
    if @entry.update_attribute(:insights, JSON.load(insights.body))
      redirect_to entry_path(@entry.id), :flash => { :success => "Watson analytics updated sucessfully." }
    end
  end

  def multi_select
    if !!params[:entries_ids]
      @multi_select = Entry.find(params[:entries_ids])
    else
      flash.now[:error] = "You didn't select any transcripts."
      render :index
    end
  end

  def analyse_all
    @multi_entry = Entry.find(params[:entries_ids])
    @multi_entry.each do |entry|
      profile_api_url = "#{Figaro.env.bluemix_url}/v2/profile"
      client = RestClient::Resource.new(profile_api_url, Figaro.env.bluemix_username, Figaro.env.bluemix_password)
      insights = client.post entry.transcript, :content_type => "text/plain;charset=utf-8"
      entry.update_attribute(:insights, JSON.load(insights.body))
    end
    redirect_to entries_path, :flash => { :success => "Watson analytics updated sucessfully on multiple selections." }
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def update
    @entry = Entry.find(params[:id])
    if @entry.update_attributes(entry_params)
      redirect_to entries_path, :flash => { :success => "Record for #{@entry.company_name} updated Sucessfully." }
    else
      @entry.errors.full_messages.each do |msg|
        flash.now[:error] = msg
      end
      render :edit 
    end
  end

  def delete_all
    @entries = Entry.all.where(:user_id => current_user.id)
    @entries.delete_all
    redirect_to entries_path, :flash => { :warning => "All previously imported transcripts are removed." }
  end

  def destroy 
    @entry = Entry.find(params[:id])
    @entry.delete
    redirect_to entries_path
  end

  def upload
    #helper method defined in upload_helper.rb
    if !params[:file]
      flash.now[:error] = "No file selected, please try again!" 
      render :new
    else
      process_upload(params[:file])
    end
  end

  def linkedin
    redirect_to "https://www.linkedin.com/pub/dir/?first=" + params[:firstname] + "&last="\
    + params[:lastname] + "&search=Search"
  end

end



private
# def analyse(input)
#   profile_api_url = "#{Figaro.env.bluemix_url}/v2/profile"
#   client = RestClient::Resource.new(profile_api_url, Figaro.env.bluemix_username, Figaro.env.bluemix_password)
#   insights = client.post input, :content_type => "text/plain;charset=utf-8"
#   @watson_says = JSON.load(insights.body)
# end

def entry_params
  params.require(:entry).permit(:company_name, :ticker, :event_name, :date, :speaker_name, :speaker_title, :wcount, :transcript, :insights)
end

app/controllers/entry_controller.rb
class EntryController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
    @input = params[:input]
    analyse(@input)
    render new_entry_path
  end

  def edit
  end

  def delete
  end

end

private
  def analyse(input)
    profile_api_url = "#{Figaro.env.bluemix_url}/v2/profile"

    client = RestClient::Resource.new(profile_api_url, Figaro.env.bluemix_username, Figaro.env.bluemix_password)
    insights = client.post input, :content_type => "text/plain"

    @pipeline = JSON.load(insights.body)
  end

app/views/entries/_form.html.erb
<h3>Event details</h3>
<p>*Please verify your input</p>
<%= form_for @entry, :html => {:class => "form-group"} do |f| %>
<%= f.label :company_name %> <br>
<%= f.text_field :company_name, :class => "form-control" %> <br>
<%= f.label :event_name %> <br>
<%= f.text_field :event_name, :class => "form-control" %> <br>
<%= f.label :date %> <br>
<%= f.text_field :date, :class => "form-control" %> 


<h3>Corporate Participants</h3>
<% @result.each do |person| %>
<%= f.radio_button(:speaker_name, person[0], :class => "speakerRadio") %>
<%= f.label(:speaker_name, person[0], :value => person[0]) %>
<br>
<% end %>	


<%= tag("div", :id => "transcript", :"data-content" => @result.to_h.to_json) %>

<div style = "float:right">	
	<label> Word count: </label>
	<span id="wcount"></span>
</div>
<%= f.text_area :transcript, :class => "form-control transBox", :placeholder => "Please select speaker." %>
<br>
<%= f.submit "Capture", :id=>"submitButton", :class => "btn btn-success" %>
<% end %>

app/views/entries/edit.html.erb
<div class="page-header">
	<h1>Edit event details</h1>
</div>
<%= form_for @entry, :html => {:class => "form-group"} do |f| %>
	<div class= "col-lg-6">	
		<%= f.label :company_name %> <br>
		<%= f.text_field :company_name, :class => "form-control" %> <br>
	</div>
	<div class= "col-lg-6">
		<%= f.label :ticker %> <br>
		<%= f.text_field :ticker, :class => "form-control" %> <br>
	</div>
	<div class= "col-md-6">
		<%= f.label :event_name %> <br>
		<%= f.text_field :event_name, :class => "form-control" %> <br>
	</div>
	<div class= "col-md-6">
		<%= f.label :date %> <br>
		<%= f.text_field :date, :class => "form-control" %> <br>
	</div>
	<div class= "col-md-6">
		<%= f.label :speaker_name %> <br>
		<%= f.text_field :speaker_name, :class => "form-control" %> <br> 
	</div>
	<div class= "col-md-6">
		<%= f.label :speaker_title %> <br>
		<%= f.text_field :speaker_title, :class => "form-control" %> <br>
	</div>
	<div class= "col-md-12">
		<%= f.label :wcount %> <br>
		<%= f.text_field :wcount, :class => "form-control" %> <br>
	</div>
	<div class= "col-md-12">
		<%= f.label :transcript %> <br>
		<%= f.text_area :transcript, :class => "form-control transBox" %> <br>
	</div>

	<div class="form-group">
	  <%= f.submit "Save", class: "btn btn-w-m btn-info" %>
	  <%= link_to 'Delete', @entry, class: "btn btn-w-m btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
	  <%= link_to 'Cancel', entries_path, class: "btn btn-w-m btn-defaults" %>
	</div>
<% end %>

app/views/entries/index.html.erb
<h1>Imported transcripts</h1>

<!-- <div class = 'pull-right linkedin_form'>
	<%#= form_tag(entries_linkedin_path,:method => :post) do %>
		First Name: <%#= text_field_tag(:firstname) %>
		Last Name: <%#= text_field_tag(:lastname) %>
	  	<%#= submit_tag("Linkedin Search", :class=>"btn btn-default") %>
	<%# end %>
</div> -->
<hr>
<!-- Below form_tag is for run Watson analytics on multiple selections -->
<%#= form_tag analyse_all_path do %>
<%= form_tag new_user_report_path(current_user), method: :get do %>
	<table class = 'table table-striped table-bordered table-condensed' id = 'allEntries'>
		<thead>
			<th class='align-center'><%= check_box_tag "select_all" %></th>
			<th >Company Name</th>
			<th >Ticker</th>
			<th >Event Name</th>
			<th >Date</th>
			<th >Speaker</th>
			<th >Title</th>
			<th >Word Count</th>
			<th ></th>
		</thead>
		<tbody>
			<% current_user.entries.each do |e| %>
				<tr>
					<td class='align-center'><%= check_box_tag "entries_ids[]", e.id %></td>
					<td><%= e.company_name %></td>
					<td><%= e.ticker %></td>
					<td><%= e.event_name %></td>
					<td><%= e.date.strftime('%m/%d/%Y') %></td>
					<td><%= e.speaker_name %></td>
					<td><%= e.speaker_title %></td>
					<td class='align-center'><%= e.wcount %></td>
					<td class='align-center'>
						<%= link_to 'Show', entry_path(e.id), method: :get, :class => "btn btn-primary" %> 
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<%= submit_tag "Analyse Checked", :class => 'btn btn-primary btn-lg' %>
  <%= link_to 'Delete All', entries_delete_all_path, :class => "btn btn-danger btn-lg", data: { confirm: 'Are you sure you want to remove all imported transcripts?' } %>
<% end %>

<br>

app/views/entries/landing.html.erb
<div class="jumbotron">
	<h1 style='color:white'>Behavioral Finance<br>
		<small>Executive Personality Analysis</small></h1>
  <p style='color:white'>This application utilizes the IBM Watson's linguistic analytic algorithm to infer cognitive and social characteristics, including Big Five, Values, and Needs, from the quarterly earnings call transcripts of publically traded companies. By deriving cognitive and social preferences, the service helps users to understand the managers of these companies at a more personalized level.</p>
	<br>
	<br>
	<%= link_to 'Enter', entries_path, method: :get, :class => 'col-md-offset-4 col-md-4 btn btn-default btn-lg' %>
	<br>
	<br>
	<br>
	<br>
</div>

app/views/entries/multi_select.html.erb
<h1>Run Watson Analytics</h1>
<hr>
<%= form_tag :html => {:class => "form-group"} do %>
	<div class='row'>	
		<div class= "col-lg-6">	
			<%= label_tag :company_name %> <br>
			<%= text_field_tag :company_name, @multi_select.first.company_name, :class => "form-control" %> <br>
		</div>
		<div class= "col-lg-6">
			<%= label_tag :ticker %> <br>
			<%= text_field_tag :ticker, @multi_select.first.ticker, :class => "form-control" %> <br>
		</div>
		<div class= "col-md-6">
			<%= label_tag :speaker_name %> <br>
			<%= text_field_tag :speaker_name, @multi_select.first.speaker_name, :class => "form-control" %> <br> 
		</div>
		<div class= "col-md-6">
			<%= label_tag :speaker_title %> <br>
			<%= text_field_tag :speaker_title, @multi_select.first.speaker_title, :class => "form-control" %> <br>
		</div>
		<div class= "col-md-12">
			<%= label_tag :wcount, "Total word count" %> <small><i>NOTE:</i> Watson needs a minimum of 3,500, preferably 6,000 or more, to compute statistically significant estimates</small><br>
			<%= text_field_tag :wcount, @multi_select.sum{|x| x.wcount}, :class => "form-control" %> <br>
		</div>
		<%= f.hidden_field :transcript, value: @combined %>
	</div>
	<%= submit_tag "Run Watson Analytics", :class=> "btn btn-primary btn-lg" %>
	<%= link_to "Back", :back, :class=> "btn btn-default btn-lg" %>
<% end %>
	<hr>
	
	<% @multi_select.each do |s| %>
		<div class= "well well-sm col-md-5 col-md-offset-1">
			<%= label_tag :event_name %> <br>
			<%= text_field_tag :event_name, s.event_name, readonly: true, :class => "form-control" %> <br>
			<%= label_tag :speaker_name %> <br>
			<%= text_field_tag :speaker_name, s.speaker_name, readonly: true, :class => "form-control" %> <br> 
			<%= label_tag :transcript %> <br>
			<%= text_area_tag :transcript, s.transcript, readonly: true, :class => "form-control transBox" %> <br>
			<p class="text-right">word count: <span class="badge"><%= s.wcount %></span></p>
		</div>
<%#= selection.speaker_name %>
	<%#= render 'selection' %>
	<% end %>

app/views/entries/new.html.erb
<!-- upload txt file -->
<%= form_tag 'upload', :multipart => true, :class => "well" do %>
<h3>Upload transcript text File</h3> 
<%= file_field_tag "file" %> <br>
<%= submit_tag 'Upload', :class => "btn btn-primary" %>
<% end %>

<% if @result %>
	<%= render partial: "form" %>
<% end %>


<p>For individual transcript upload, please upload *.txt file.</p>
<p>For batch upload, please upload *.zip file which only consist of *.txt files.</p>

app/views/entries/show.html.erb
<div class="page-header">
	<h1><%= @entry.speaker_name %> <small><%= @entry.speaker_title %></small></h1>
</div>
<h3><%= @entry.company_name %> (<%= @entry.ticker %>) - <%= @entry.event_name %></h3>
<h4><%= @entry.date.strftime('%A, %d %b %Y') %></h4>

<%= link_to 'Edit transcript', edit_entry_path(@entry), method: :get, :class => "btn btn-lg btn-primary" %>  
<%= link_to "Back", :back, :class => "btn btn-lg btn-default" %>

<!-- Temporarily removing Watson Analytics for single transcript -->
<!-- <%# if @entry.insights != nil %>
	<button class="btn btn-lg btn-primary" type="button" data-toggle="collapse" data-target="#collapseTranscript" aria-expanded="false" aria-controls="collapseTranscript">
		Show Transcript <span class="badge"><%= @entry.wcount %> words</span>
	</button>
	<div class="collapse" id="collapseTranscript">
		<div class="well">
			<%#= @entry.transcript %>
		</div>
	</div>
	<button class="btn btn-lg btn-success" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
		Show raw JSON results from Watson
	</button>
	<%#= link_to "Export As CSV", export_csv_path(@entry.id), method: :post, :class => "btn btn-lg btn-default" %>
	<div class="collapse" id="collapseExample">
		<div class="well">
			<%= @entry.insights %>
		</div>
	</div>
	<div class ="row">
		<div class="col-md-6">
			<%#= render partial: "big5" %>
		</div>
		<div class="col-md-6">
			<%#= render partial: "values" %>
			<%#= render partial: "needs" %>
		</div>
	</div>

	<br>
<%# else %> -->
	<br>
	<br>
	<label>Transcript: </label>
	<br>
	<%= text_area_tag 'transcript', @entry.transcript, readonly: true, :class => 'form-control transBox' %>
	<p class="text-right">word count: <span class="badge"><%= @entry.wcount %></span></p>
	
	<!-- Temporarily removed button to run Watson analytics on sigle transcrip -->
	<%#= button_to "Run Watson Analytics", analyse_path(@entry), :class=> "btn btn-primary btn-lg" %>
<%# end %>
<%= link_to 'Delete', entry_path(@entry), method: :delete, :class => "btn btn-danger", data: { confirm: 'Are you sure?' } %>
<br>
<br>