config/routes.rb
Rails.application.routes.draw do

  resources :password_resets, only: [:create, :edit, :update]

  root 'entries#landing'

  post 'entries/upload' => 'entries#upload'
  post 'entries/:id/analyse' => 'entries#analyse', as: :analyse
  post 'entries/analyse_all' => 'entries#analyse_all', as: :analyse_all
  post 'users/:user_id/reports/:id/export_csv' => 'reports#export_csv', as: :export_csv
  get 'entries/delete_all' => 'entries#delete_all'

  resources :user_sessions
  resources :entries
  resources :users do
    resources :reports
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:student_id], params[:password])
      redirect_back_or_to(entries_path, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(root_path, notice: 'Logged out!')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_forgot_password_form.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <div class="field col-md-6 col-md-offset-3">
    <%= label_tag :email %><br />
    <%= text_field_tag :email, nil,:class => "form-control" %> 
    <br>
    <%= submit_tag "Reset my password!", class: "btn btn-w-m btn-danger" %>
  </div>
<% end %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post, :html => {:class => "form-group"} do |f| %>
	<div class= "col-md-6 col-md-offset-3">	
		<%= label_tag :student_id, "Student Number" %> <br>
		<%= text_field_tag :student_id, nil ,:class => "form-control" %> <br>
	</div>
	<div class= "col-md-6 col-md-offset-3">
		<%= label_tag :password %> <br>
		<%= password_field_tag :password, nil ,:class => "form-control" %> <br>
	</div>
	
	<div class="col-md-6 col-md-offset-3">
	  <%= submit_tag "Login", class: "btn btn-w-m btn-info" %>

	  <%= link_to 'Cancel', root_path, class: "btn btn-w-m btn-defaults" %>
	</div>
<% end %>

app/views/user_sessions/new.html.erb
<div class="page-header">
	<h1>Login</h1>
</div>

<%= render 'form' %>

<div class='row'></div>
<br>
<br>
<!-- <div class = 'row'></div> -->
<!-- <div class = 'well'> -->
<div class="page-header">
	<h1>Forgot Password?</h1>
</div>
<%= render 'forgot_password_form' %>
<!-- </div> -->