config/routes.rb
Rails.application.routes.draw do

  resources :password_resets, only: [:create, :edit, :update]

  root 'entries#landing'

  post 'entries/upload' => 'entries#upload'
  post 'entries/:id/analyse' => 'entries#analyse', as: :analyse
  post 'entries/analyse_all' => 'entries#analyse_all', as: :analyse_all
  post 'users/:user_id/reports/:id/export_csv' => 'reports#export_csv', as: :export_csv
  get 'entries/delete_all' => 'entries#delete_all'

  resources :user_sessions
  resources :entries
  resources :users do
    resources :reports
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Personality Insight" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    
    <%= render 'favicon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-header">
          <a class="navbar-brand" href="/">
            <%= image_tag "favicon/favicon-16x16.png" %>
          </a>
        </div>
        <%= link_to "Contrarian Labs", root_path, :class => "navbar-brand"  %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "View Transcripts", entries_path  %></li>
            <li><%= link_to "Upload new Transcripts", new_entry_path  %></li>
            <% if current_user %>
              <li><%= link_to "My Reports", user_reports_path(current_user) %></li>
            <% end %>
            <!-- <li><%#= link_to "About", "/path3"  %></li> -->
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li><%= link_to "Login as: #{current_user.first_name} #{current_user.last_name}", edit_user_path(current_user.id) %></li>
              <li><a href="">Reports generated: <strong><%= current_user.report_creations %>/100</strong></a></li>
              <li><%= link_to "Logout", :logout, method: :post %></li>
            <% else %>
              <li><%= link_to "Register", new_user_path %></li>
              <li><%= link_to "Login", :login %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <!-- <div class="col-lg-9"> -->
          <%= bootstrap_flash %>
          <%= yield %>

      </div><!--/row-->

     

    </div> <!-- /container -->

  </body>

  <footer class="footer-distributed" id="footer">
    <div class="container">
      <div class="footer-right">
        <%= link_to "mailto:help@contrarianlabs.ca" do %>
          <i class="fa fa-envelope"> <span id="email-us">Email us for help</span></i>
        <% end %>
<!--         <a id="email-us" href="mailto:help@contrarianlabs.ca"><i class="fa fa-envelope"> Email us for help</i></a> -->
      </div>
      <div class="footer-left">
        <p class="footer-links">
          <%= link_to "Home", root_path  %>
          ·
          <%= link_to "View Transcripts", entries_path  %>
          ·
          <%= link_to "Upload new Transcripts", new_entry_path  %>
          <% if current_user %>
            ·
            <%= link_to "My Reports", user_reports_path(current_user) %>
          <% end %>
        </p>
        <p>Contrarian Labs Co. &copy; 2016</p>
      </div>
    </div>
  </footer>
</html>